#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let's install one!
# Requirements:
    # Install nginx on your web-01 server
    # Nginx should be listening on port 80
    # When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Holberton School
    # As an answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements

apt-get install nginx -y
rm /usr/share/nginx/html/index.html
echo "Holberton School" > /usr/share/nginx/html/index.html
service nginx restart
